[buildPlans.IosevkaCurly]
family = "Iosevka Curly"
spacing = "normal"
serifs = "sans"
noCvSs = true
exportGlyphNames = false
digit-form = 'old-style'

  [buildPlans.IosevkaCurly.variants]
  inherits = "ss20"

    [buildPlans.IosevkaCurly.variants.design]
    digit-form = "old-style"
    capital-a = "straight-serifless"
    capital-q = "crossing-curly-tailed"
    e = "rounded"
    f = "serifless"
    i = "serifed-semi-tailed"
    l = "serifed-semi-tailed"
    y = "cursive-serifless"

[buildPlans.IosevkaCurly.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCurly.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCurly.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCurly.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.IosevkaCurls]
family = "Iosevka Curls"
spacing = "quasi-proportional"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
digit-form = 'old-style'

  [buildPlans.IosevkaCurls.variants]
  inherits = "ss20"

    [buildPlans.IosevkaCurls.variants.design]
    digit-form = "old-style"
    capital-q = "crossing-curly-tailed"
    i = "serifed-semi-tailed"
    l = "serifed-semi-tailed"
    y = "cursive-motion-serifed"

[buildPlans.IosevkaCurls.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCurls.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaCurls.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCurls.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

